version: 2

models:
  - name: stg_invoices
    description: "Cleaned 1:1 view of raw.invoices"
    columns:
      - name: invoice_no
        tests: [not_null]
      - name: stock_code
        tests: [not_null]
      - name: quantity
        tests: [not_null]
      - name: unit_price
        tests: [not_null]
      - name: invoice_ts
        tests: [not_null]
      - name: customer_id
        tests: []   # allow null if raw has anonymous rows
